name = "vault-api"
main = "src/index.ts"
assets = { directory = "./public", binding = "ASSETS" }
compatibility_date = "2026-05-26"

[[d1_databases]]
binding = "DB"
database_name = "vault"
database_id = "fd908dfe-2770-4e57-aba3-e7a867babd25"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "CACHE"
id = "3093266e5c694331b39e4b9c0b1207e7"

[observability.logs]
enabled = true
invocation_logs = true

[vars]
ENVIRONMENT = "production"
TEAM_DOMAIN = "https://nameless-resonance-af6e.cloudflareaccess.com"
#POLICY_AUD = "replace-with-your-access-application-aud-tag"
